# Generated by Django 6.0.5 on 2026-05-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_temp_email_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
