# Generated by Django 6.0.5 on 2026-07-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_gold_expires_at_user_is_referral_rewarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_profit',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
