# Generated by Django 6.0.5 on 2026-06-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['id']},
        ),
    ]
