# Generated by Django 6.0.5 on 2026-06-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_return_requested',
            field=models.BooleanField(default=False),
        ),
    ]
