# Generated by Django 6.0.5 on 2026-06-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
