# Generated by Django 6.0.5 on 2026-06-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariant_is_active_alter_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='offer_type',
            field=models.CharField(choices=[('none', 'No Offer'), ('percentage', 'Percentage Discount'), ('flat', 'Flat Discount')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='offer_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
