# Generated by Django 6.0.5 on 2026-06-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_total_sales_productvariant_offer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
