# Generated by Django 6.0.5 on 2026-07-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productvariant_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_ratings_count',
            new_name='total_reviews',
        ),
        migrations.RemoveField(
            model_name='product',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
