# Generated by Django 6.0.5 on 2026-07-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_total_ratings_count_product_total_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='min_product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='offer_type',
            field=models.CharField(choices=[('none', 'No Offer'), ('percentage', 'Percentage Discount'), ('flat', 'Flat Discount')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='offer_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
